### ISSUE TITLE
Size mismatch for model.encoder.embed_positions.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024])

### ISSUE THREAD

**Issue by anhductn2001** [AmineAmor10/pegasus_longformer#2]
I followed the readme.md but still have this problem
```
(datn) E:\Pegasus_with_Longformer_summarization-main>bash tune.sh  
2022-12-28 13:12:18.111864: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
12/28/2022 13:12:19 - WARNING - __main__ -   Process rank: -1, device: cpu, n_gpu: 0distributed training: False, 16-bits training: False
12/28/2022 13:12:19 - INFO - __main__ -   Training/evaluation parameters Seq2SeqTrainingArguments(output_dir='saved/', overwrite_output_dir=True, do_train=True, do_eval=True, do_predict=False, evaluation_strategy=<IntervalStrategy.EPOCH: 'epoch'>, prediction_loss_only=False, per_device_train_batch_size=16, per_device_eval_batch_size=16, per_gpu_train_batch_size=None, per_gpu_eval_batch_size=None, gradient_accumulation_steps=1, eval_accumulation_steps=None, learning_rate=5e-05, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=90.0, max_steps=-1, lr_scheduler_type=<SchedulerType.LINEAR: 'linear'>, warmup_ratio=0.0, warmup_steps=0, logging_dir='runs\\Dec28_13-12-19_DESKTOP-2UN4G9U', logging_strategy=<IntervalStrategy.STEPS: 'steps'>, logging_first_step=False, logging_steps=500, save_strategy=<IntervalStrategy.STEPS: 'steps'>, save_steps=1000, save_total_limit=10, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', fp16_backend='auto', fp16_full_eval=False, local_rank=-1, tpu_num_cores=None, tpu_metrics_debug=False, debug=False, dataloader_drop_last=False, eval_steps=500, dataloader_num_workers=0, past_index=-1, run_name='saved/', disable_tqdm=False, remove_unused_columns=True, label_names=None, load_best_model_at_end=False, metric_for_best_model=None, greater_is_better=None, ignore_data_skip=False, sharded_ddp=[], deepspeed=None, label_smoothing_factor=0.0, adafactor=False, group_by_length=False, length_column_name='length', report_to=['tensorboard'], ddp_find_unused_parameters=None, dataloader_pin_memory=True, skip_memory_metrics=False, mp_parameters='', sortish_sampler=False, predict_with_generate=True)
12/28/2022 13:12:20 - WARNING - datasets.builder -   Using custom data configuration default-9fa2ab968471e110
12/28/2022 13:12:20 - WARNING - datasets.builder -   Reusing dataset json (C:\Users\klinh\.cache\huggingface\datasets\json\default-9fa2ab968471e110\0.0.0\ac0ca5f5289a6cf108e706efcf040422dbbfa8e658dee6a819f20d76bb84d26b)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.07s/it] 
loading configuration file Pegasus_4k/config.json
Model config PegasusConfig {
  "activation_dropout": 0.1,
  "activation_function": "relu",
  "add_bias_logits": false,
  "add_final_layer_norm": true,
  "architectures": [
    "PegasusForConditionalGeneration"
  ],
  "attention_dilation": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
  ],
  "attention_dropout": 0.1,
  "attention_mode": "sliding_chunks",
  "attention_probs_dropout_prob": 0.1,
  "attention_window": [
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512
  ],
  "autoregressive": false,
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 1024,
  "decoder_attention_heads": 16,
  "decoder_ffn_dim": 4096,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 4,
  "decoder_start_token_id": 0,
  "dropout": 0.1,
  "encoder_attention_heads": 16,
  "encoder_ffn_dim": 4096,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 16,
  "eos_token_id": 1,
  "extra_pos_embeddings": 1,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 1,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "length_penalty": 0.8,
  "max_decoder_position_embeddings": 1024,
  "max_encoder_position_embeddings": 4096,
  "max_length": 128,
  "max_position_embeddings": 1024,
  "model_type": "pegasus",
  "normalize_before": true,
  "normalize_embedding": false,
  "num_beams": 8,
  "num_hidden_layers": 16,
  "pad_token_id": 0,
  "save_step": 15,
  "scale_embedding": true,
  "static_position_embeddings": true,
  "transformers_version": "4.5.1",
  "use_cache": true,
  "vocab_size": 96103
}

loading configuration file Pegasus_4k/config.json
Model config PegasusConfig {
  "activation_dropout": 0.1,
  "activation_function": "relu",
  "add_bias_logits": false,
  "add_final_layer_norm": true,
  "architectures": [
    "PegasusForConditionalGeneration"
  ],
  "attention_dilation": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
  ],
  "attention_dropout": 0.1,
  "attention_mode": "sliding_chunks",
  "attention_probs_dropout_prob": 0.1,
  "attention_window": [
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512
  ],
  "autoregressive": false,
  "bos_token_id": 0,
  "classif_dropout": 0.0,
  "classifier_dropout": 0.0,
  "d_model": 1024,
  "decoder_attention_heads": 16,
  "decoder_ffn_dim": 4096,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 4,
  "decoder_start_token_id": 0,
  "dropout": 0.1,
  "encoder_attention_heads": 16,
  "encoder_ffn_dim": 4096,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 16,
  "eos_token_id": 1,
  "extra_pos_embeddings": 1,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 1,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "length_penalty": 0.8,
  "max_decoder_position_embeddings": 1024,
  "max_encoder_position_embeddings": 4096,
  "max_length": 128,
  "max_position_embeddings": 1024,
  "model_type": "pegasus",
  "normalize_before": true,
  "normalize_embedding": false,
  "num_beams": 8,
  "num_hidden_layers": 16,
  "pad_token_id": 0,
  "save_step": 15,
  "scale_embedding": true,
  "static_position_embeddings": true,
  "transformers_version": "4.5.1",
  "use_cache": true,
  "vocab_size": 96103
}

Didn't find file Pegasus_4k/tokenizer.json. We won't load it.
Didn't find file Pegasus_4k/added_tokens.json. We won't load it.
loading file Pegasus_4k/spiece.model
loading file None
loading file None
loading file Pegasus_4k/special_tokens_map.json
loading file Pegasus_4k/tokenizer_config.json
loading weights file Pegasus_4k/pytorch_model.bin
Some weights of the model checkpoint at Pegasus_4k/ were not used when initializing PegasusForConditionalGeneration: ['model.encoder.layers.0.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.0.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.0.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.0.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.0.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.0.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.0.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.0.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.0.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.0.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.0.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.0.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.0.self_attn.output.weight', 'model.encoder.layers.0.self_attn.output.bias', 'model.encoder.layers.1.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.1.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.1.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.1.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.1.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.1.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.1.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.1.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.1.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.1.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.1.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.1.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.1.self_attn.output.weight', 'model.encoder.layers.1.self_attn.output.bias', 'model.encoder.layers.2.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.2.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.2.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.2.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.2.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.2.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.2.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.2.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.2.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.2.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.2.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.2.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.2.self_attn.output.weight', 'model.encoder.layers.2.self_attn.output.bias', 'model.encoder.layers.3.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.3.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.3.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.3.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.3.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.3.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.3.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.3.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.3.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.3.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.3.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.3.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.3.self_attn.output.weight', 'model.encoder.layers.3.self_attn.output.bias', 'model.encoder.layers.4.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.4.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.4.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.4.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.4.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.4.self_attn.longformer_self_attn.value.bias', 
'model.encoder.layers.4.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.4.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.4.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.4.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.4.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.4.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.4.self_attn.output.weight', 'model.encoder.layers.4.self_attn.output.bias', 'model.encoder.layers.5.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.5.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.5.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.5.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.5.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.5.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.5.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.5.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.5.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.5.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.5.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.5.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.5.self_attn.output.weight', 'model.encoder.layers.5.self_attn.output.bias', 'model.encoder.layers.6.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.6.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.6.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.6.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.6.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.6.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.6.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.6.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.6.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.6.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.6.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.6.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.6.self_attn.output.weight', 'model.encoder.layers.6.self_attn.output.bias', 'model.encoder.layers.7.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.7.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.7.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.7.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.7.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.7.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.7.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.7.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.7.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.7.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.7.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.7.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.7.self_attn.output.weight', 'model.encoder.layers.7.self_attn.output.bias', 'model.encoder.layers.8.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.8.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.8.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.8.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.8.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.8.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.8.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.8.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.8.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.8.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.8.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.8.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.8.self_attn.output.weight', 'model.encoder.layers.8.self_attn.output.bias', 'model.encoder.layers.9.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.9.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.9.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.9.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.9.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.9.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.9.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.9.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.9.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.9.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.9.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.9.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.9.self_attn.output.weight', 'model.encoder.layers.9.self_attn.output.bias', 'model.encoder.layers.10.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.10.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.10.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.10.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.10.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.10.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.10.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.10.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.10.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.10.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.10.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.10.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.10.self_attn.output.weight', 'model.encoder.layers.10.self_attn.output.bias', 'model.encoder.layers.11.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.11.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.11.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.11.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.11.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.11.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.11.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.11.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.11.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.11.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.11.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.11.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.11.self_attn.output.weight', 'model.encoder.layers.11.self_attn.output.bias', 'model.encoder.layers.12.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.12.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.12.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.12.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.12.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.12.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.12.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.12.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.12.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.12.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.12.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.12.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.12.self_attn.output.weight', 'model.encoder.layers.12.self_attn.output.bias', 'model.encoder.layers.13.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.13.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.13.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.13.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.13.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.13.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.13.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.13.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.13.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.13.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.13.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.13.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.13.self_attn.output.weight', 'model.encoder.layers.13.self_attn.output.bias', 'model.encoder.layers.14.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.14.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.14.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.14.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.14.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.14.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.14.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.14.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.14.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.14.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.14.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.14.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.14.self_attn.output.weight', 'model.encoder.layers.14.self_attn.output.bias', 'model.encoder.layers.15.self_attn.longformer_self_attn.query.weight', 'model.encoder.layers.15.self_attn.longformer_self_attn.query.bias', 'model.encoder.layers.15.self_attn.longformer_self_attn.key.weight', 'model.encoder.layers.15.self_attn.longformer_self_attn.key.bias', 'model.encoder.layers.15.self_attn.longformer_self_attn.value.weight', 'model.encoder.layers.15.self_attn.longformer_self_attn.value.bias', 'model.encoder.layers.15.self_attn.longformer_self_attn.query_global.weight', 'model.encoder.layers.15.self_attn.longformer_self_attn.query_global.bias', 'model.encoder.layers.15.self_attn.longformer_self_attn.key_global.weight', 'model.encoder.layers.15.self_attn.longformer_self_attn.key_global.bias', 'model.encoder.layers.15.self_attn.longformer_self_attn.value_global.weight', 'model.encoder.layers.15.self_attn.longformer_self_attn.value_global.bias', 'model.encoder.layers.15.self_attn.output.weight', 'model.encoder.layers.15.self_attn.output.bias']
- This IS expected if you are initializing PegasusForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing PegasusForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at Pegasus_4k/ and are newly initialized: ['model.encoder.layers.0.self_attn.k_proj.weight', 'model.encoder.layers.0.self_attn.k_proj.bias', 'model.encoder.layers.0.self_attn.v_proj.weight', 'model.encoder.layers.0.self_attn.v_proj.bias', 'model.encoder.layers.0.self_attn.q_proj.weight', 'model.encoder.layers.0.self_attn.q_proj.bias', 'model.encoder.layers.0.self_attn.out_proj.weight', 'model.encoder.layers.0.self_attn.out_proj.bias', 'model.encoder.layers.1.self_attn.k_proj.weight', 'model.encoder.layers.1.self_attn.k_proj.bias', 'model.encoder.layers.1.self_attn.v_proj.weight', 'model.encoder.layers.1.self_attn.v_proj.bias', 'model.encoder.layers.1.self_attn.q_proj.weight', 'model.encoder.layers.1.self_attn.q_proj.bias', 'model.encoder.layers.1.self_attn.out_proj.weight', 'model.encoder.layers.1.self_attn.out_proj.bias', 'model.encoder.layers.2.self_attn.k_proj.weight', 'model.encoder.layers.2.self_attn.k_proj.bias', 'model.encoder.layers.2.self_attn.v_proj.weight', 'model.encoder.layers.2.self_attn.v_proj.bias', 'model.encoder.layers.2.self_attn.q_proj.weight', 'model.encoder.layers.2.self_attn.q_proj.bias', 'model.encoder.layers.2.self_attn.out_proj.weight', 'model.encoder.layers.2.self_attn.out_proj.bias', 'model.encoder.layers.3.self_attn.k_proj.weight', 'model.encoder.layers.3.self_attn.k_proj.bias', 'model.encoder.layers.3.self_attn.v_proj.weight', 'model.encoder.layers.3.self_attn.v_proj.bias', 'model.encoder.layers.3.self_attn.q_proj.weight', 'model.encoder.layers.3.self_attn.q_proj.bias', 'model.encoder.layers.3.self_attn.out_proj.weight', 'model.encoder.layers.3.self_attn.out_proj.bias', 'model.encoder.layers.4.self_attn.k_proj.weight', 'model.encoder.layers.4.self_attn.k_proj.bias', 'model.encoder.layers.4.self_attn.v_proj.weight', 'model.encoder.layers.4.self_attn.v_proj.bias', 'model.encoder.layers.4.self_attn.q_proj.weight', 'model.encoder.layers.4.self_attn.q_proj.bias', 'model.encoder.layers.4.self_attn.out_proj.weight', 'model.encoder.layers.4.self_attn.out_proj.bias', 'model.encoder.layers.5.self_attn.k_proj.weight', 'model.encoder.layers.5.self_attn.k_proj.bias', 'model.encoder.layers.5.self_attn.v_proj.weight', 'model.encoder.layers.5.self_attn.v_proj.bias', 'model.encoder.layers.5.self_attn.q_proj.weight', 'model.encoder.layers.5.self_attn.q_proj.bias', 'model.encoder.layers.5.self_attn.out_proj.weight', 'model.encoder.layers.5.self_attn.out_proj.bias', 'model.encoder.layers.6.self_attn.k_proj.weight', 'model.encoder.layers.6.self_attn.k_proj.bias', 'model.encoder.layers.6.self_attn.v_proj.weight', 'model.encoder.layers.6.self_attn.v_proj.bias', 'model.encoder.layers.6.self_attn.q_proj.weight', 'model.encoder.layers.6.self_attn.q_proj.bias', 'model.encoder.layers.6.self_attn.out_proj.weight', 'model.encoder.layers.6.self_attn.out_proj.bias', 'model.encoder.layers.7.self_attn.k_proj.weight', 'model.encoder.layers.7.self_attn.k_proj.bias', 'model.encoder.layers.7.self_attn.v_proj.weight', 'model.encoder.layers.7.self_attn.v_proj.bias', 'model.encoder.layers.7.self_attn.q_proj.weight', 'model.encoder.layers.7.self_attn.q_proj.bias', 'model.encoder.layers.7.self_attn.out_proj.weight', 'model.encoder.layers.7.self_attn.out_proj.bias', 'model.encoder.layers.8.self_attn.k_proj.weight', 'model.encoder.layers.8.self_attn.k_proj.bias', 'model.encoder.layers.8.self_attn.v_proj.weight', 'model.encoder.layers.8.self_attn.v_proj.bias', 'model.encoder.layers.8.self_attn.q_proj.weight', 'model.encoder.layers.8.self_attn.q_proj.bias', 'model.encoder.layers.8.self_attn.out_proj.weight', 'model.encoder.layers.8.self_attn.out_proj.bias', 'model.encoder.layers.9.self_attn.k_proj.weight', 'model.encoder.layers.9.self_attn.k_proj.bias', 'model.encoder.layers.9.self_attn.v_proj.weight', 'model.encoder.layers.9.self_attn.v_proj.bias', 'model.encoder.layers.9.self_attn.q_proj.weight', 'model.encoder.layers.9.self_attn.q_proj.bias', 'model.encoder.layers.9.self_attn.out_proj.weight', 'model.encoder.layers.9.self_attn.out_proj.bias', 'model.encoder.layers.10.self_attn.k_proj.weight', 'model.encoder.layers.10.self_attn.k_proj.bias', 'model.encoder.layers.10.self_attn.v_proj.weight', 'model.encoder.layers.10.self_attn.v_proj.bias', 'model.encoder.layers.10.self_attn.q_proj.weight', 'model.encoder.layers.10.self_attn.q_proj.bias', 'model.encoder.layers.10.self_attn.out_proj.weight', 'model.encoder.layers.10.self_attn.out_proj.bias', 'model.encoder.layers.11.self_attn.k_proj.weight', 'model.encoder.layers.11.self_attn.k_proj.bias', 'model.encoder.layers.11.self_attn.v_proj.weight', 'model.encoder.layers.11.self_attn.v_proj.bias', 'model.encoder.layers.11.self_attn.q_proj.weight', 'model.encoder.layers.11.self_attn.q_proj.bias', 'model.encoder.layers.11.self_attn.out_proj.weight', 'model.encoder.layers.11.self_attn.out_proj.bias', 'model.encoder.layers.12.self_attn.k_proj.weight', 'model.encoder.layers.12.self_attn.k_proj.bias', 'model.encoder.layers.12.self_attn.v_proj.weight', 'model.encoder.layers.12.self_attn.v_proj.bias', 'model.encoder.layers.12.self_attn.q_proj.weight', 'model.encoder.layers.12.self_attn.q_proj.bias', 'model.encoder.layers.12.self_attn.out_proj.weight', 'model.encoder.layers.12.self_attn.out_proj.bias', 'model.encoder.layers.13.self_attn.k_proj.weight', 'model.encoder.layers.13.self_attn.k_proj.bias', 'model.encoder.layers.13.self_attn.v_proj.weight', 'model.encoder.layers.13.self_attn.v_proj.bias', 'model.encoder.layers.13.self_attn.q_proj.weight', 'model.encoder.layers.13.self_attn.q_proj.bias', 'model.encoder.layers.13.self_attn.out_proj.weight', 'model.encoder.layers.13.self_attn.out_proj.bias', 'model.encoder.layers.14.self_attn.k_proj.weight', 'model.encoder.layers.14.self_attn.k_proj.bias', 'model.encoder.layers.14.self_attn.v_proj.weight', 'model.encoder.layers.14.self_attn.v_proj.bias', 'model.encoder.layers.14.self_attn.q_proj.weight', 'model.encoder.layers.14.self_attn.q_proj.bias', 'model.encoder.layers.14.self_attn.out_proj.weight', 'model.encoder.layers.14.self_attn.out_proj.bias', 'model.encoder.layers.15.self_attn.k_proj.weight', 'model.encoder.layers.15.self_attn.k_proj.bias', 'model.encoder.layers.15.self_attn.v_proj.weight', 'model.encoder.layers.15.self_attn.v_proj.bias', 'model.encoder.layers.15.self_attn.q_proj.weight', 'model.encoder.layers.15.self_attn.q_proj.bias', 'model.encoder.layers.15.self_attn.out_proj.weight', 'model.encoder.layers.15.self_attn.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "transformers/examples/seq2seq/run_summarization.py", line 591, in <module>
    main()
  File "transformers/examples/seq2seq/run_summarization.py", line 353, in main
    use_auth_token=True if model_args.use_auth_token else None,
  File "E:\Pegasus_with_Longformer_summarization-main\transformers\src\transformers\models\auto\auto_factory.py", line 360, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **kwargs
  File "E:\Pegasus_with_Longformer_summarization-main\transformers\src\transformers\modeling_utils.py", line 1183, in from_pretrained
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for PegasusForConditionalGeneration:
        size mismatch for model.encoder.embed_positions.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
``` `

**Comment by anhductn2001** [comment]
Can you help me @amoramine ??

**Comment by Oswald1997** [comment]
Hello, I have the same problem, have you solved it?
